common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: joshmcmillan
  password:

development:
  <<: *common
  database: hunt_development

test:
  <<: *common
  database: hunt_test

production:
  <<: *common
  database: hunt